In [1]:
import numpy as np
from numpy.random import randn

In [2]:
 #Now using numpy.where
A = np.array([1,2,3,4])
B= np.array([100,200,300,400])
#Now a boolean array to create condition
condition = np.array([True,True,False,False])
answer2 = np.where(condition,A,B)
#Show
answer2

array([  1,   2, 300, 400])

In [3]:
#Can use np.where on 2d for manipulation
arr = randn(5,5)
#Show arr
arr

array([[-1.67795679,  1.34238103, -1.70590751, -0.07144016,  0.38536956],
       [ 0.6590612 , -0.18275909,  0.26318245,  0.40880408,  0.9642533 ],
       [ 1.77848233, -1.36793698,  0.89524512, -0.64863072,  0.40959779],
       [-0.16689757,  0.09252344,  0.63908066,  0.37404143, -0.38026435],
       [ 0.60598675, -2.57586111, -0.75514811,  0.61855019, -0.64407467]])

In [4]:
#Can use np.where on 2d for manipulation
arr1 = 2+1.5*randn(5,5)
#Show arr
arr1

array([[ 2.00138553,  1.48231694,  3.09363271,  5.83701193,  0.68052675],
       [ 0.47210539,  0.97330637,  3.08909873,  1.65769188,  3.0321081 ],
       [ 0.83310425,  4.41419637,  0.64200622,  1.57363347, -0.23607118],
       [ 2.73105631,  3.16059251,  4.16022546,  2.17991117,  1.21361544],
       [ 1.20785866,  2.9912655 ,  4.15340081,  2.33628507,  0.36368848]])