In [1]:
import numpy as np #Adding numpy lib 

## Create an array by lists

In [2]:
l1=[1,2,3,4] #Normal python list

In [5]:
l1*3 #multiply list by number

[1, 2, 3, 4, 1, 2, 3, 4, 1, 2, 3, 4]

In [3]:
arry1=np.array(l1) #creating 1D array from list

In [4]:
arry1

array([1, 2, 3, 4])

In [6]:
arry1*5 #multiply array by number

array([ 5, 10, 15, 20])

In [7]:
l2=[11,22,33,44] #another array
l2

[11, 22, 33, 44]

In [8]:
l=[l1,l2] # combining two lists
l# it is not an array

[[1, 2, 3, 4], [11, 22, 33, 44]]

In [10]:
array_2D=np.array(l) #2D array
array_2D

array([[ 1,  2,  3,  4],
       [11, 22, 33, 44]])

In [11]:
array_2D.shape #check the type of the array

(2, 4)

In [12]:
array_2D.dtype #check the type of the array

dtype('int32')

## Create special array by some special function 

#### Zeros Array

In [13]:
np.zeros(3) #Special Array (Zero) without data type

array([0., 0., 0.])

In [15]:
np.zeros(3, 'int') #Special Array (Zero) with data type

array([0, 0, 0])

#### Ones Array

In [16]:
np.ones(3) #Special Array (Ones) without data type

array([1., 1., 1.])

In [17]:
np.ones(3,'int') #Special Array (Ones) with data type

array([1, 1, 1])

In [18]:
 np.ones([3,3]) #Special Array (Ones), 2D Array without data type

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [50]:
 np.ones([3,3],'int') #Special Array (Ones), 2D Array with data type

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

#### Empty Array

In [51]:
np.empty(3) #Special Array (Empty)

array([1., 1., 1.])

In [52]:
np.zeros(3) 

array([0., 0., 0.])

In [53]:
np.empty(3)

array([0., 0., 0.])

In [54]:
np.ones(3,'int')

array([1, 1, 1])

In [55]:
np.empty(3)

array([0., 0., 0.])

In [56]:
np.ones(3)

array([1., 1., 1.])

In [57]:
np.empty(3)

array([1., 1., 1.])

#### Identity Array

In [58]:
np.eye(4) ##Special Array (Identity, nxn) Array A*I=A

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

## Create Array with range function

In [59]:
np.arange(10) #Create Array with range function

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [60]:
np.arange(0,50,2) #Array with range function, start, end & increment

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32,
       34, 36, 38, 40, 42, 44, 46, 48])