In [1]:
import numpy as np #Adding numpy lib 

### 1. Creating a 1D numpy array with the integers from 0 to 9

In [2]:
l1=[0,1,2,3,4,5,6,7,8,9]

In [3]:
np.array(l1)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

   ###### Other soluation

In [5]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

### 2. Create a 2D numpy array with the shape (3,3) and fill it with zeros

In [6]:
np.zeros([3,3])

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

### 3. Create a 3D numpy array with shape(2,3,4) and fill it with ones

In [7]:
np.ones([2,3,4])

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]])

### 4. Create a numpy array with 10 random integers between 0 and 100

In [15]:
Random_Number=np.random.randint(100,size=(10))
Random_Number

array([48,  1, 41,  0, 18, 81,  9, 35, 96, 40])

### 5. Create a numpy array with 10 random flots between 0 and 1

In [19]:
Random_Number_flots=np.random.rand(10)
Random_Number_flots

array([0.6136516 , 0.63910347, 0.35642057, 0.55081723, 0.26898478,
       0.99936421, 0.90570959, 0.6818623 , 0.8900212 , 0.06416133])

### 6. Create a numpy array with 5 equally speced values between 0 and 1

In [23]:
np.arange(0,1.1,0.25)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

### 7. Create a numpy array with 5 equally speced values between 0 and 10

In [31]:
np.arange(0,10,2) 

array([0, 2, 4, 6, 8])

### 8. Create a numpy array with 5 equally speced values between -1 and 1

In [34]:
np.arange(-1,1.5,0.5) 

array([-1. , -0.5,  0. ,  0.5,  1. ])

### 9. Create a numpy array with the sine values of angles between 0 and 2pi

In [44]:
in_array = np.linspace(0, 2*np.pi,5)
out_array = np.sin(in_array)
out_array 

array([ 0.0000000e+00,  1.0000000e+00,  1.2246468e-16, -1.0000000e+00,
       -2.4492936e-16])

### 10. Create a numpy array with the cosine values of angles between 0 and pi

In [46]:
in_array1 = np.linspace(0, np.pi,5)
out_array1 = np.cos(in_array)
out_array 

array([ 0.0000000e+00,  1.0000000e+00,  1.2246468e-16, -1.0000000e+00,
       -2.4492936e-16])