In [2]:
import numpy as np

### 1. Create a 2x3 NumPy array and its transpose using the np.transpose() function

In [5]:
a=np.array([[5,6],[7,8],[9,10]])
a

array([[ 5,  6],
       [ 7,  8],
       [ 9, 10]])

In [6]:
a_t= np.transpose(a)
a_t

array([[ 5,  7,  9],
       [ 6,  8, 10]])

### 2. Create a 2x2 NumPy array and its transpose using the np.transpose() function, then calculate the dot product of the two arrays using the np.dot() function

In [7]:
b=np.array([[5,6],[7,8]])
b

array([[5, 6],
       [7, 8]])

In [9]:
b_t= np.transpose(b)
b_t

array([[5, 7],
       [6, 8]])

In [10]:
np.dot(b,b_t) 

array([[ 61,  83],
       [ 83, 113]])