In [78]:
import numpy as np

# Scalar Operations

### 1. Create a 2*2 Numpy array and multiple it by 2

In [79]:
l1=[1,2]

In [80]:
l2=[3,4]

In [81]:
l=(l1,l2)

In [82]:
array_2D_2= np.array(l)
array_2D_2

array([[1, 2],
       [3, 4]])

In [83]:
array_2D_2*2

array([[2, 4],
       [6, 8]])

### 2. Create a 3*3 Numpy array and add 5 to each element

In [84]:
l3=[5,6,7]

In [85]:
l4=[8,9,10]

In [86]:
l5=[11,12,13]

In [87]:
ll=(l3,l4,l5)
ll

([5, 6, 7], [8, 9, 10], [11, 12, 13])

In [88]:
array_2D_3= np.array(ll)
array_2D_3

array([[ 5,  6,  7],
       [ 8,  9, 10],
       [11, 12, 13]])

In [89]:
array_2D_3+5

array([[10, 11, 12],
       [13, 14, 15],
       [16, 17, 18]])

### 3. Create a 4*4 Numpy array and subtract 10 from each element 

In [90]:
array_2D_4 = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12],[13,14,15,16]])
array_2D_4

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [91]:
array_2D_4 -10

array([[-9, -8, -7, -6],
       [-5, -4, -3, -2],
       [-1,  0,  1,  2],
       [ 3,  4,  5,  6]])

### 4. Create a 5*5 Numpy array and divided each element by 2

In [92]:
array_2D_5 = np.array([[1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15],[16,17,18,19,20],[21,22,23,24,25]])

In [93]:
array_2D_5

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [94]:
array_2D_5/2

array([[ 0.5,  1. ,  1.5,  2. ,  2.5],
       [ 3. ,  3.5,  4. ,  4.5,  5. ],
       [ 5.5,  6. ,  6.5,  7. ,  7.5],
       [ 8. ,  8.5,  9. ,  9.5, 10. ],
       [10.5, 11. , 11.5, 12. , 12.5]])

### 5. Create a 6*6 Numpy array and calculate the sequare root of each element

In [95]:
array_2D_6 = np.array([[1,2,3,4,5,6],[6,7,8,9,10,11],[11,12,13,14,15,16],[16,17,18,19,20,21],[21,22,23,24,25,26],[27,28,29,30,31,32]])

In [96]:
array_2D_6

array([[ 1,  2,  3,  4,  5,  6],
       [ 6,  7,  8,  9, 10, 11],
       [11, 12, 13, 14, 15, 16],
       [16, 17, 18, 19, 20, 21],
       [21, 22, 23, 24, 25, 26],
       [27, 28, 29, 30, 31, 32]])

In [97]:
np.sqrt(array_2D_6)

array([[1.        , 1.41421356, 1.73205081, 2.        , 2.23606798,
        2.44948974],
       [2.44948974, 2.64575131, 2.82842712, 3.        , 3.16227766,
        3.31662479],
       [3.31662479, 3.46410162, 3.60555128, 3.74165739, 3.87298335,
        4.        ],
       [4.        , 4.12310563, 4.24264069, 4.35889894, 4.47213595,
        4.58257569],
       [4.58257569, 4.69041576, 4.79583152, 4.89897949, 5.        ,
        5.09901951],
       [5.19615242, 5.29150262, 5.38516481, 5.47722558, 5.56776436,
        5.65685425]])

# Matrix product and Multiplication

### 1. Create two 2*2 Numpy arrays and calculate their product using the np.matmul() function

In [98]:
a = np.array([[1,2],[3,4]])
a

array([[1, 2],
       [3, 4]])

In [99]:
b = np.array([[5,6],[7,8]])
b

array([[5, 6],
       [7, 8]])

In [100]:
np.matmul(a,b)

array([[19, 22],
       [43, 50]])

### 2 . Create two 3*3 Numpy arrays and calculate their product using  the np.dot() function

In [101]:
c = np.array([[1,2,3],[3,4,5],[6,7,8]])
d = np.array([[9,10,11],[12,3,14],[15,16,17]])

In [102]:
np.dot(c, d)

array([[ 78,  64,  90],
       [150, 122, 174],
       [258, 209, 300]])

### 3.Create two 2 * 3 Numpy array and  3 * 2 Numpy array and calculate their product using the np.matmul function 

In [103]:
e= np.array([[1,2,3],[3,4,5]])

In [104]:
f=np.array([[5,6],[7,8],[9,10]])

In [105]:
np.matmul(e,f)

array([[ 46,  52],
       [ 88, 100]])

### 4. Create a 3x2 NumPy array and a 2x3 NumPy array, and calculate their product using the np.dot() function 

In [106]:
np.dot(e,f)

array([[ 46,  52],
       [ 88, 100]])

### 5. Create a 4x4 NumPy array and its transpose using the np.transpose() function, then calculate their product using the np.matmul() function.

In [107]:
aa = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12],[13,14,15,16]])
aa

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [108]:
aa_t = np.transpose(aa) # same if i use this line of code aa.T
aa_t

array([[ 1,  5,  9, 13],
       [ 2,  6, 10, 14],
       [ 3,  7, 11, 15],
       [ 4,  8, 12, 16]])

In [109]:
np.matmul(aa,aa_t)

array([[ 30,  70, 110, 150],
       [ 70, 174, 278, 382],
       [110, 278, 446, 614],
       [150, 382, 614, 846]])