# Array Indexing

In [35]:
import numpy as np

### 1. Create a 1D NumPy array with the integers from 0 to 9. Extract the 3rd element from the array

In [36]:
a = np.array([0,1,2,3,4,5,6,7,8,9])
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [37]:
a[2]

2

### 2.Create a 2D NumPy array with shape (3, 3) and fill it with random numbers. Extract the element at row 2, column 1.

In [38]:
b= np.random.randint(100,size=(3,3), dtype='int')
b

array([[17,  5,  2],
       [91, 21,  6],
       [95, 46, 86]])

In [39]:
b[1][0]

91

### 3. Create a 2D NumPy array with shape (4, 4) and fill it with random numbers. Extract the subarray consisting of the first 2 rows and the last 2 columns.

In [40]:
c = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12],[13,14,15,16]])
c

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [41]:
c[:2,2:]

array([[3, 4],
       [7, 8]])

### 4. Create a 1D NumPy array with the integers from 0 to 9. Copy a slice of the array consisting of the first 3 elements.

In [42]:
d = np.array([0,1,2,3,4,5,6,7,8,9])
d

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [43]:
d[:3]

array([0, 1, 2])

### 5. Create a 2D NumPy array with shape (3, 3) and fill it with random numbers. Copy a slice of the array consisting of the first 2 rows and the first 2 columns.

In [44]:
e= np.random.randint(100,size=(3,3), dtype='int')
e

array([[96, 65, 95],
       [73, 22, 62],
       [38, 36, 84]])

In [45]:
e[:2,1:]

array([[65, 95],
       [22, 62]])

### 6.Create a 1D NumPy array with the integers from 0 to 9. Reshape the array into a 2D array with shape (3, 3)

In [53]:
f = np.array([0,1,2,3,4,5,6,7,8])
f

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [54]:
f.reshape(3, 3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

### 7.Create a 2D NumPy array with shape (4, 4) and fill it with random numbers. Reshape the array into a 1D array

In [59]:
g= np.random.randint(100,size=(4,4), dtype='int')
g

array([[55, 23, 91, 52],
       [65, 66, 50, 41],
       [90, 12, 93, 45],
       [ 3, 82,  7, 56]])

In [60]:
g.flatten()

array([55, 23, 91, 52, 65, 66, 50, 41, 90, 12, 93, 45,  3, 82,  7, 56])

### 8.Create two 1D NumPy arrays with the integers from 0 to 4. Concatenate the two arrays into a single 1D array