# Array Processing

#### 1. Create a NumPy array with 10 random integers between 0 and 100

In [16]:
import numpy as np
import random
import statistics

In [7]:
a= np.random.randint(101,size=10, dtype='int')
a

array([97, 96,  5, 56, 78, 86, 56, 81, 37, 41])

#### 2. Use the np.where() function to create a new array with the same shape as the previous one, where values less than 50 are replaced with -1 and values greater than or equal to 50 are replaced with 1.

In [18]:
b= np.where(a<50,-1,1)
b

array([ 1,  1, -1,  1,  1,  1,  1,  1, -1, -1])

#### 3. Calculate the mean, median, and standard deviation of the original array.

In [19]:
a.mean()

63.3

In [20]:
statistics.median(a)

67.0

In [21]:
statistics.stdev(a)

29.698484809834994

#### 4. Create a boolean array that is True where the values in the original array are even, and False otherwise.

In [22]:
c = np.where(a%2 == 0,'True', 'False')
c

array(['False', 'True', 'False', 'True', 'True', 'True', 'True', 'False',
       'False', 'False'], dtype='<U5')

#### 5. Sort the original array in ascending order.

In [26]:
d = sorted(a)
d

[5, 37, 41, 56, 56, 78, 81, 86, 96, 97]

#### 6. Find the unique values in the original array.

In [27]:
np.unique(a)

array([ 5, 37, 41, 56, 78, 81, 86, 96, 97])

#### 7. Use the np.in1d() function to create a boolean array indicating which elements of the original array are also present in a new array with 5 random integers between 0 and 100.

In [28]:
c=np.random.randint(101,size=5, dtype='int')
c

array([60, 99, 83, 86, 20])

In [29]:
 np.in1d(a,c) 

array([False, False, False, False, False, False, False,  True, False,
       False])

#### 8. Save the original array to a text file named "my_array.txt" using the np.savetxt() function.

In [32]:
d= np.savetxt("my_array.txt",a)
d