# Series

#### 1. Create a Series using the following data: data = [10, 20, 30, 40, 50]

In [2]:
import numpy as np
#import the pandas lib
import pandas as pd
from pandas import Series,DataFrame

In [3]:
data = [10, 20, 30, 40, 50]
s = Series(data)
s

0    10
1    20
2    30
3    40
4    50
dtype: int64

#### 2. Assign the following index labels to the Series: index = ['a', 'b', 'c', 'd', 'e']

In [4]:
s.index =  ['a', 'b', 'c', 'd', 'e']
s

a    10
b    20
c    30
d    40
e    50
dtype: int64

#### 3. Use index values to select the values of the Series for the labels 'b' and 'e'.

In [5]:
s['b']

20

In [6]:
s['e']

50

#### 4. Check if the Series contains the value 20 using a boolean array.

In [7]:
s.isin([20])

a    False
b     True
c    False
d    False
e    False
dtype: bool

In [8]:
s.isin([20]).any()

True

#### 5. Check if the Series contains the values 15 and 20 using a boolean array.

In [9]:
s.isin([15,20])

a    False
b     True
c    False
d    False
e    False
dtype: bool

#### 6. Add the value 5 to each element of the Series using array operations.


In [10]:
series = np.array([1, 2, 3, 4, 5])
series+5

array([ 6,  7,  8,  9, 10])

#### 7. Convert the Series into a Python dictionary and check its values.

In [11]:
series_1 = np.array([1, 2, 3, 4, 5])
series_1

array([1, 2, 3, 4, 5])

In [12]:
dictionary = {}
for index, value in enumerate(series_1):
    dictionary[index] = value
print(dictionary)

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5}


#### 8. Pass a dictionary to the Series constructor and assign the following keys and values:{'a': 10, 'b': 20, 'c': 30, 'd': 40, 'e': 50, 'f': 60}

In [13]:
dictionary = {'a': 10, 'b': 20, 'c': 30, 'd': 40, 'e': 50, 'f': 60}

series_2 = pd.Series(dictionary)

print(series_2)

a    10
b    20
c    30
d    40
e    50
f    60
dtype: int64


#### 9. Check if any values in the Series are null or not null using isnull() and notnull() methods

In [14]:
Series_3 = np.array([1, 2, 3, np.nan, 5, 6])

null_values = np.isnan(Series_3)

print(null_values)

[False False False  True False False]


In [15]:
not_null_values = ~np.isnan(Series_3)
not_null_values

array([ True,  True,  True, False,  True,  True])

#### 10. Create another Series using the following data: data2 = [20, 30, 40, 50, 60]

In [16]:
data2 = [20, 30, 40, 50, 60]
series2 = pd.Series(data2)
print(series2)

0    20
1    30
2    40
3    50
4    60
dtype: int64


#### 11. Assign the following index labels to the second Series: index2 = ['b', 'c', 'd', 'e', 'f']

In [17]:
index2 = ['b', 'c', 'd', 'e', 'f']
series3 = pd.Series(data2, index=index2)
series3

b    20
c    30
d    40
e    50
f    60
dtype: int64

#### 12. Add the two Series together and observe how pandas automatically aligns the data based on their index labels.

In [18]:
data1 = [10, 20, 30, 40, 50]
index1 = ['a', 'b', 'c', 'd', 'e']

data2 = [20, 30, 40, 50, 60]
index2 = ['b', 'c', 'd', 'e', 'f']

series4 = pd.Series(data1, index=index1)
series5= pd.Series(data2, index=index2)

print(series4 + series5)

a      NaN
b     40.0
c     60.0
d     80.0
e    100.0
f      NaN
dtype: float64


#### 13. Use the unique() method to find the unique values in the Series.

In [19]:
data3 = [20, 30, 40, 50, 60,20,10,40]
np.unique(data3)

array([10, 20, 30, 40, 50, 60])

#### 14. Use the sort_values() method to sort the Series in ascending order by value.

In [20]:
data4 = [10,60,40, 20, 30,15, 40, 50,5, 15]
index1 = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j']

series1 = pd.Series(data4, index=index1)

print(series1.sort_values())


i     5
a    10
f    15
j    15
d    20
e    30
c    40
g    40
h    50
b    60
dtype: int64


#### 15. Save the Series to a text file using the to_csv() method.

In [21]:
data5 = [10,60,40, 20, 30,15, 40, 50,5, 15]
series1 = pd.Series(data5)
series1.to_csv('series.csv')